//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.31 at 11:52:53 AM EAT 
//


package co.ke.emtechhouse.eims.Finacle.filookups.schemecodes;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BodyDESCRIPTION_QNAME = new QName("", "DESCRIPTION");
    private final static QName _BodySCHMECODE_QNAME = new QName("", "SCHME_CODE");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SchemeCodesBody }
     * 
     */
    public SchemeCodesBody createBody() {
        return new SchemeCodesBody();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DESCRIPTION", scope = SchemeCodesBody.class)
    public JAXBElement<String> createBodyDESCRIPTION(String value) {
        return new JAXBElement<String>(_BodyDESCRIPTION_QNAME, String.class, SchemeCodesBody.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SCHME_CODE", scope = SchemeCodesBody.class)
    public JAXBElement<String> createBodySCHMECODE(String value) {
        return new JAXBElement<String>(_BodySCHMECODE_QNAME, String.class, SchemeCodesBody.class, value);
    }

}
