//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.05 at 04:04:46 PM EAT 
//


package co.ke.emtechhouse.eims.TransactionComponent.FinacleService.EmtFailureResponse;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ResponseHeader">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RequestMessageKey">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="ResponseMessageInfo">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="UBUSTransaction">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="HostTransaction">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="HostParentTransaction">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="CustomInfo" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RateCodesBody">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Error">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="FISystemException">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ErrorDetail">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                                                 &lt;element name="ErrorDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="ErrorType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "body"
})
@XmlRootElement(name = "FIXML")
public class FIXML {

    @XmlElement(name = "Header", required = true)
    protected Header header;
    @XmlElement(name = "RateCodesBody", required = true)
    protected Body body;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link Body }
     *     
     */
    public Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link Body }
     *     
     */
    public void setBody(Body value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Error">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="FISystemException">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ErrorDetail">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *                                       &lt;element name="ErrorDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="ErrorType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "error"
    })
    public static class Body {

        @XmlElement(name = "Error", required = true)
        protected Error error;

        /**
         * Gets the value of the error property.
         * 
         * @return
         *     possible object is
         *     {@link Error }
         *     
         */
        public Error getError() {
            return error;
        }

        /**
         * Sets the value of the error property.
         * 
         * @param value
         *     allowed object is
         *     {@link Error }
         *     
         */
        public void setError(Error value) {
            this.error = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="FISystemException">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ErrorDetail">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
         *                             &lt;element name="ErrorDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="ErrorType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fiSystemException"
        })
        public static class Error {

            @XmlElement(name = "FISystemException", required = true)
            protected FISystemException fiSystemException;

            /**
             * Gets the value of the fiSystemException property.
             * 
             * @return
             *     possible object is
             *     {@link FISystemException }
             *     
             */
            public FISystemException getFISystemException() {
                return fiSystemException;
            }

            /**
             * Sets the value of the fiSystemException property.
             * 
             * @param value
             *     allowed object is
             *     {@link FISystemException }
             *     
             */
            public void setFISystemException(FISystemException value) {
                this.fiSystemException = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ErrorDetail">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
             *                   &lt;element name="ErrorDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="ErrorType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "errorDetail"
            })
            public static class FISystemException {

                @XmlElement(name = "ErrorDetail", required = true)
                protected ErrorDetail errorDetail;

                /**
                 * Gets the value of the errorDetail property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ErrorDetail }
                 *     
                 */
                public ErrorDetail getErrorDetail() {
                    return errorDetail;
                }

                /**
                 * Sets the value of the errorDetail property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ErrorDetail }
                 *     
                 */
                public void setErrorDetail(ErrorDetail value) {
                    this.errorDetail = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
                 *         &lt;element name="ErrorDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="ErrorType" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "errorCode",
                    "errorDesc",
                    "errorType"
                })
                public static class ErrorDetail {

                    @XmlElement(name = "ErrorCode")
                    @XmlSchemaType(name = "unsignedShort")
                    protected int errorCode;
                    @XmlElement(name = "ErrorDesc", required = true)
                    protected String errorDesc;
                    @XmlElement(name = "ErrorType", required = true)
                    protected String errorType;

                    /**
                     * Gets the value of the errorCode property.
                     * 
                     */
                    public int getErrorCode() {
                        return errorCode;
                    }

                    /**
                     * Sets the value of the errorCode property.
                     * 
                     */
                    public void setErrorCode(int value) {
                        this.errorCode = value;
                    }

                    /**
                     * Gets the value of the errorDesc property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getErrorDesc() {
                        return errorDesc;
                    }

                    /**
                     * Sets the value of the errorDesc property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setErrorDesc(String value) {
                        this.errorDesc = value;
                    }

                    /**
                     * Gets the value of the errorType property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getErrorType() {
                        return errorType;
                    }

                    /**
                     * Sets the value of the errorType property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setErrorType(String value) {
                        this.errorType = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ResponseHeader">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RequestMessageKey">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="ResponseMessageInfo">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="UBUSTransaction">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="HostTransaction">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="HostParentTransaction">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="CustomInfo" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "responseHeader"
    })
    public static class Header {

        @XmlElement(name = "ResponseHeader", required = true)
        protected ResponseHeader responseHeader;

        /**
         * Gets the value of the responseHeader property.
         * 
         * @return
         *     possible object is
         *     {@link ResponseHeader }
         *     
         */
        public ResponseHeader getResponseHeader() {
            return responseHeader;
        }

        /**
         * Sets the value of the responseHeader property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResponseHeader }
         *     
         */
        public void setResponseHeader(ResponseHeader value) {
            this.responseHeader = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RequestMessageKey">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="ResponseMessageInfo">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="UBUSTransaction">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="HostTransaction">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="HostParentTransaction">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="CustomInfo" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "requestMessageKey",
            "responseMessageInfo",
            "ubusTransaction",
            "hostTransaction",
            "hostParentTransaction",
            "customInfo"
        })
        public static class ResponseHeader {

            @XmlElement(name = "RequestMessageKey", required = true)
            protected RequestMessageKey requestMessageKey;
            @XmlElement(name = "ResponseMessageInfo", required = true)
            protected ResponseMessageInfo responseMessageInfo;
            @XmlElement(name = "UBUSTransaction", required = true)
            protected UBUSTransaction ubusTransaction;
            @XmlElement(name = "HostTransaction", required = true)
            protected HostTransaction hostTransaction;
            @XmlElement(name = "HostParentTransaction", required = true)
            protected HostParentTransaction hostParentTransaction;
            @XmlElement(name = "CustomInfo", required = true)
            protected Object customInfo;

            /**
             * Gets the value of the requestMessageKey property.
             * 
             * @return
             *     possible object is
             *     {@link RequestMessageKey }
             *     
             */
            public RequestMessageKey getRequestMessageKey() {
                return requestMessageKey;
            }

            /**
             * Sets the value of the requestMessageKey property.
             * 
             * @param value
             *     allowed object is
             *     {@link RequestMessageKey }
             *     
             */
            public void setRequestMessageKey(RequestMessageKey value) {
                this.requestMessageKey = value;
            }

            /**
             * Gets the value of the responseMessageInfo property.
             * 
             * @return
             *     possible object is
             *     {@link ResponseMessageInfo }
             *     
             */
            public ResponseMessageInfo getResponseMessageInfo() {
                return responseMessageInfo;
            }

            /**
             * Sets the value of the responseMessageInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link ResponseMessageInfo }
             *     
             */
            public void setResponseMessageInfo(ResponseMessageInfo value) {
                this.responseMessageInfo = value;
            }

            /**
             * Gets the value of the ubusTransaction property.
             * 
             * @return
             *     possible object is
             *     {@link UBUSTransaction }
             *     
             */
            public UBUSTransaction getUBUSTransaction() {
                return ubusTransaction;
            }

            /**
             * Sets the value of the ubusTransaction property.
             * 
             * @param value
             *     allowed object is
             *     {@link UBUSTransaction }
             *     
             */
            public void setUBUSTransaction(UBUSTransaction value) {
                this.ubusTransaction = value;
            }

            /**
             * Gets the value of the hostTransaction property.
             * 
             * @return
             *     possible object is
             *     {@link HostTransaction }
             *     
             */
            public HostTransaction getHostTransaction() {
                return hostTransaction;
            }

            /**
             * Sets the value of the hostTransaction property.
             * 
             * @param value
             *     allowed object is
             *     {@link HostTransaction }
             *     
             */
            public void setHostTransaction(HostTransaction value) {
                this.hostTransaction = value;
            }

            /**
             * Gets the value of the hostParentTransaction property.
             * 
             * @return
             *     possible object is
             *     {@link HostParentTransaction }
             *     
             */
            public HostParentTransaction getHostParentTransaction() {
                return hostParentTransaction;
            }

            /**
             * Sets the value of the hostParentTransaction property.
             * 
             * @param value
             *     allowed object is
             *     {@link HostParentTransaction }
             *     
             */
            public void setHostParentTransaction(HostParentTransaction value) {
                this.hostParentTransaction = value;
            }

            /**
             * Gets the value of the customInfo property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getCustomInfo() {
                return customInfo;
            }

            /**
             * Sets the value of the customInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setCustomInfo(Object value) {
                this.customInfo = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "id",
                "status"
            })
            public static class HostParentTransaction {

                @XmlElement(name = "Id", required = true)
                protected Object id;
                @XmlElement(name = "Status", required = true)
                protected Object status;

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setId(Object value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the status property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getStatus() {
                    return status;
                }

                /**
                 * Sets the value of the status property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setStatus(Object value) {
                    this.status = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "id",
                "status"
            })
            public static class HostTransaction {

                @XmlElement(name = "Id", required = true)
                protected Object id;
                @XmlElement(name = "Status", required = true)
                protected String status;

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setId(Object value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the status property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStatus() {
                    return status;
                }

                /**
                 * Sets the value of the status property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStatus(String value) {
                    this.status = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "requestUUID",
                "serviceRequestId",
                "serviceRequestVersion",
                "channelId"
            })
            public static class RequestMessageKey {

                @XmlElement(name = "RequestUUID", required = true)
                protected Object requestUUID;
                @XmlElement(name = "ServiceRequestId", required = true)
                protected Object serviceRequestId;
                @XmlElement(name = "ServiceRequestVersion", required = true)
                protected Object serviceRequestVersion;
                @XmlElement(name = "ChannelId", required = true)
                protected Object channelId;

                /**
                 * Gets the value of the requestUUID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getRequestUUID() {
                    return requestUUID;
                }

                /**
                 * Sets the value of the requestUUID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setRequestUUID(Object value) {
                    this.requestUUID = value;
                }

                /**
                 * Gets the value of the serviceRequestId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getServiceRequestId() {
                    return serviceRequestId;
                }

                /**
                 * Sets the value of the serviceRequestId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setServiceRequestId(Object value) {
                    this.serviceRequestId = value;
                }

                /**
                 * Gets the value of the serviceRequestVersion property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getServiceRequestVersion() {
                    return serviceRequestVersion;
                }

                /**
                 * Sets the value of the serviceRequestVersion property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setServiceRequestVersion(Object value) {
                    this.serviceRequestVersion = value;
                }

                /**
                 * Gets the value of the channelId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getChannelId() {
                    return channelId;
                }

                /**
                 * Sets the value of the channelId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setChannelId(Object value) {
                    this.channelId = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "bankId",
                "timeZone",
                "messageDateTime"
            })
            public static class ResponseMessageInfo {

                @XmlElement(name = "BankId", required = true)
                protected Object bankId;
                @XmlElement(name = "TimeZone", required = true)
                protected Object timeZone;
                @XmlElement(name = "MessageDateTime", required = true)
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar messageDateTime;

                /**
                 * Gets the value of the bankId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getBankId() {
                    return bankId;
                }

                /**
                 * Sets the value of the bankId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setBankId(Object value) {
                    this.bankId = value;
                }

                /**
                 * Gets the value of the timeZone property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getTimeZone() {
                    return timeZone;
                }

                /**
                 * Sets the value of the timeZone property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setTimeZone(Object value) {
                    this.timeZone = value;
                }

                /**
                 * Gets the value of the messageDateTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getMessageDateTime() {
                    return messageDateTime;
                }

                /**
                 * Sets the value of the messageDateTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setMessageDateTime(XMLGregorianCalendar value) {
                    this.messageDateTime = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "id",
                "status"
            })
            public static class UBUSTransaction {

                @XmlElement(name = "Id", required = true)
                protected Object id;
                @XmlElement(name = "Status", required = true)
                protected String status;

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setId(Object value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the status property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStatus() {
                    return status;
                }

                /**
                 * Sets the value of the status property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStatus(String value) {
                    this.status = value;
                }

            }

        }

    }

}
