//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.01 at 09:40:45 AM EAT 
//


package co.ke.emtechhouse.eims.Finacle.filookups.accounts;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="FORACID" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *           &lt;element name="ACCT_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="ACCT_CURRENCY" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="CLR_BAL_AMT" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "foracidOrACCTNAMEOrACCTCURRENCY"
})
@XmlRootElement(name = "body")
public class AccountsListBody {

    @XmlElementRefs({
        @XmlElementRef(name = "FORACID", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CLR_BAL_AMT", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ACCT_NAME", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ACCT_CURRENCY", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PARTITIONED_FLG", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<? extends Serializable>> foracidOrACCTNAMEOrACCTCURRENCY;

    /**
     * Gets the value of the foracidOrACCTNAMEOrACCTCURRENCY property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the foracidOrACCTNAMEOrACCTCURRENCY property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFORACIDOrACCTNAMEOrACCTCURRENCY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends Serializable>> getFORACIDOrACCTNAMEOrACCTCURRENCY() {
        if (foracidOrACCTNAMEOrACCTCURRENCY == null) {
            foracidOrACCTNAMEOrACCTCURRENCY = new ArrayList<JAXBElement<? extends Serializable>>();
        }
        return this.foracidOrACCTNAMEOrACCTCURRENCY;
    }

}
