//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.06 at 03:55:04 PM EAT 
//


package co.ke.emtechhouse.eims.Finacle.filookups.branches;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="SOL_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "solidOrDESCRIPTION"
})
@XmlRootElement(name = "body")
public class BranchesBody {

    @XmlElementRefs({
        @XmlElementRef(name = "SOL_ID", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DESCRIPTION", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<String>> solidOrDESCRIPTION;

    /**
     * Gets the value of the solidOrDESCRIPTION property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the solidOrDESCRIPTION property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSOLIDOrDESCRIPTION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getSOLIDOrDESCRIPTION() {
        if (solidOrDESCRIPTION == null) {
            solidOrDESCRIPTION = new ArrayList<JAXBElement<String>>();
        }
        return this.solidOrDESCRIPTION;
    }

}
