import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "MENUITEMS.MAIN.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  {
    path: "/admin/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
  {
    path: "",
    title: "PARAMETER SETTINGS",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["View General Parameters"],
    submenu: [],
  },
  {
    path: "",
    title: "Parameters",
    moduleName: "parameters",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["View General Parameters", "View Tax Parameters", "View Invoices Tax Parameters", "View Invoices Profile Parameters","View Expense Categories", "View Expense SubCategories", "View Suppliers", "View Expenses", "View Cost Centers", "Add Cost Centers",],
    submenu: [
      {
        path: "/admin/parameters/general",
        title: "General",
        moduleName: "parameters",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View General Parameters"],
        submenu: [],
      },
      {
        path: "/admin/parameters/tax",
        title: "Tax parameters",
        moduleName: "parameters",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Tax Parameters"],
        submenu: [],
      },
      {
        path: "/admin/parameters/invoice-taxes",
        title: "Invoice Taxes",
        moduleName: "invoice-taxes",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Invoices Tax Parameters"],
        submenu: [],
      },
      {
        path: "/admin/parameters/invoice-profile",
        title: "Invoice Profile",
        moduleName: "invoice-profile",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View General Parameters"],
        submenu: [],
      },
      {
        path: "/admin/parameters/organistaion-basic-details",
        title: "Organisation Details",
        moduleName: "organisation-details",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Invoices Profile Parameters"],
        submenu: [],
      },
    ],
  },


  {
    path: "/admin/supplier/categories-management",
    title: "Expense Categories",
    moduleName: "categories-management",
    iconType: "feather",
    icon: "menu",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["View Expense Categories"],
    submenu: [],
  },
  {
    path: "/admin/supplier/sub-categories-management",
    title: "Expense Subcategories",
    moduleName: "subcategories",
    iconType: "feather",
    icon: "layers",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["View Expense SubCategories"],
    submenu: [],
  },

  {
    path: "",
    title: "Suppliers",
    moduleName: "suppliers-management",
    iconType: "feather",
    icon: "sun",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["View Suppliers"],
    submenu: [
      {
        path: "/admin/supplier/suppliers-management/add-supplier",
        title: "Add Supplier",
        moduleName: "add-supplier",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Add Suppliers"],
        submenu: [],
      },
      {
        path: "/admin/supplier/suppliers-management/all",
        title: "View Suppliers",
        moduleName: "view-suppliers",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Suppliers"],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Expenses",
    moduleName: "expenses-management",
    iconType: "feather",
    icon: "dollar-sign",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["View Expenses"],
    submenu: [
      {
        path: "/admin/supplier/expenses-management/add-expense",
        title: "Add Expense",
        moduleName: "add-expense",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Add Expenses"],
        submenu: [],
      },
      {
        path: "/admin/supplier/expenses-management/all",
        title: "View Expenses",
        moduleName: "view-expenses",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Expenses"],
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "Cost Centers",
    moduleName: "cost-centers-management",
    iconType: "feather",
    icon: "credit-card",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["View Cost Centers", "Add Cost Centers"],
    submenu: [
      {
        path: "/admin/supplier/cost-centers-management/add-cost-center",
        title: "Add CostCenter",
        moduleName: "add-costcenter",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Add Cost Centers"],
        submenu: [],
      },
      {
        path: "/admin/supplier/cost-centers-management/all",
        title: "View Expenses",
        moduleName: "add-costcenter",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Cost Centers"],
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "PURCHASE ORDER MANAGEMENT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: [ "View PurchaseOrders"],
    submenu: [],
  },
  {
    path: "",
    title: "Purchase Orders",
    moduleName: "supplier",
    iconType: "feather",
    icon: "shopping-bag",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["View PurchaseOrders"],
    submenu: [
      {
        path: "/admin/supplier/purchase-orders-management/create-purchase-order",
        title: "Add Purchase Order",
        moduleName: "supplier",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Add PurchaseOrders", "View PurchaseOrders"],
        submenu: [],
      },
      {
        path: "/admin/supplier/purchase-orders-management/all",
        title: "View Purchase Orders",
        moduleName: "supplier",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View PurchaseOrders"],
        submenu: [],
      },
      {
        path: "/admin/supplier/purchase-orders-management/rejected-purchase-orders",
        title: "Rejected Purchase Orders",
        moduleName: "supplier",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View PurchaseOrders"],
        submenu: [],
      },
    ],
  },
  {
    path: "/admin/acknowledgement",
    title: "Active POs'",
    moduleName: "acknowledgement",
    iconType: "feather",
    icon: "check-circle",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Confirm Approved PurchaseOrders", "View Unpaid PurchaseOrders", "Pay PurchaseOrders", "View Paid PurchaseOrders"],
    submenu: [
      {
        path: "/admin/acknowledgement/active-pos",
        title: "Approved Purchase Orders",
        moduleName: "acknowledgement",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Confirm Approved PurchaseOrders"],
        submenu: [],
      },

      {
        path: "/admin/acknowledgement/unpaid-pos",
        title: "Unpaid Purchase Orders",
        moduleName: "acknowledgement",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Unpaid PurchaseOrders"],
        submenu: [],
      },
      {
        path: "/admin/acknowledgement/paid-pos",
        title: "Paid Purchase Orders",
        moduleName: "acknowledgement",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Paid PurchaseOrders"],
        submenu: [],
      },
      {
        path: "/admin/acknowledgement/canceled-pos",
        title: "Canceled Purchase Orders",
        moduleName: "acknowledgement",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Unpaid PurchaseOrders"],
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "Bills and Transactions",
    moduleName: "acknowledgement",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Enter Accrual", "Enter Transaction"],
    submenu: [],
  },

  
  // {
  //   path: "",
  //   title: "Bills",
  //   moduleName: "bills",
  //   iconType: "feather",
  //   icon: "book",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["All"],
  //   privilege: ["Enter Transaction"],
  //   submenu: [
  //     {
  //       path: "/admin/bills/pay-bill",
  //       title: "Pay Bill",
  //       moduleName: "bills",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Enter Transaction"],
  //       submenu: [],
  //     },


  //     {
  //       path: "/admin/bills/pending-bills",
  //       title: "Pending bills",
  //       moduleName: "bills",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Enter Transaction"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/admin/bills/rejected-bills",
  //       title: "Rejected bills",
  //       moduleName: "bills",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Enter Transaction"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/admin/bills/paid-bills",
  //       title: "Paid bills",
  //       moduleName: "bills",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Enter Transaction"],
  //       submenu: [],
  //     },
  //   ],
  // },

  // {
  //   path: "",
  //   title: "Payables",
  //   moduleName: "transactions",
  //   iconType: "feather",
  //   icon: "book",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["All"],
  //   privilege: ["Enter Accrual"],
  //   submenu: [
  //     {
  //       path: "/admin/transactions/add-transaction-supplier",
  //       title: "Accrual suppliers",
  //       moduleName: "transactions",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Enter Accrual"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/admin/transactions/post-transaction",
  //       title: "Post single accrual",
  //       moduleName: "transactions",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Enter Accrual"],
  //       submenu: [],
  //     },

  //     {
  //       path: "/admin/transactions/post-multi-transactions",
  //       title: "Post multi-accruals",
  //       moduleName: "transactions",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Enter Accrual"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/admin/transactions/pending-transactions",
  //       title: "Pending transactions",
  //       moduleName: "transactions",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Enter Accrual"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/admin/transactions/rejected-transactions",
  //       title: "Rejected transactions",
  //       moduleName: "transactions",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Enter Accrual"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/admin/transactions/posted-transactions",
  //       title: "Posted transactions",
  //       moduleName: "transactions",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Enter Accrual"],
  //       submenu: [],
  //     },
  //   ],
  // },

  {
    path: "",
    title: "Direct Transactions",
    moduleName: "transfer-transactions",
    iconType: "feather",
    icon: "book",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Enter Transaction"],
    submenu: [

      {
        path: "/admin/transfer-transactions/post-direct-transaction",
        title: "Post transaction",
        moduleName: "transfer-transactions",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Enter Transaction"],
        submenu: [],
      },

      {
        path: "/admin/transfer-transactions/pending-direct-transactions",
        title: "Pending Transactions",
        moduleName: "transfer-transactions",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Enter Transaction"],
        submenu: [],
      },
      {
        path: "/admin/transfer-transactions/approved-direct-transactions",
        title: "Posted Transactions",
        moduleName: "transfer-transactions",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Enter Transaction"],
        submenu: [],
      },
      {
        path: "/admin/transfer-transactions/rejected-direct-transactions",
        title: "Rejected Transactions",
        moduleName: "transfer-transactions",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Enter Transaction"],
        submenu: [],
      },
      {
        path: "/admin/transfer-transactions/deleted-direct-transactions",
        title: "Deleted Transactions",
        moduleName: "transfer-transactions",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Enter Transaction"],
        submenu: [],
      },

    ],
  },

  {
    path: "",
    title: "INVOICE MANAGEMENT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["Add Stock", "View Stock", "Add Customer","View Customers", "Add Invoice", "View Invoices","View Credit Notes"],
    submenu: [],
  },
  {
    path: "",
    title: "Stock Management",
    moduleName: "items",
    iconType: "feather",
    icon: "shopping-cart",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["Add Stock", "View Stock"],
    submenu: [
      {
        path: "/admin/customer/items-management/add-item",
        title: "Add Commodity",
        moduleName: "add-customer",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Add Stock"],
        submenu: [],
      },
      {
        path: "/admin/customer/items-management/all-items",
        title: "All Commodities",
        moduleName: "add-customer",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Stock"],
        submenu: [],
      },
      {
        path: "/admin/customer/items-management/item-services",
        title: "Services Only",
        moduleName: "services-only",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Stock"],
        submenu: [],
      },
      {
        path: "/admin/customer/items-management/item-goods",
        title: "Goods Only",
        moduleName: "goods-only",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Stock"],
        submenu: [],
      },
      {
        path: "/admin/customer/items-management/failed-ura-uploads",
        title: "Failed Uploads",
        moduleName: "failed-uploads",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Stock"],
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "Customers Management",
    moduleName: "customers-management",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["Add Customer","View Customers"],
    submenu: [
      {
        path: "/admin/customer/customers-management/add-customer",
        title: "Add Customer",
        moduleName: "add-customer",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Add Customer"],
        submenu: [],
      },
      {
        path: "/admin/customer/customers-management/all-customers",
        title: "View Customers",
        moduleName: "view-customers",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Customers"],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Invoice Management",
    moduleName: "invoice-management",
    iconType: "feather",
    icon: "file-text",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["Add Invoice", "View Invoices"],
    submenu: [
      {
        path: "/admin/customer/invoices-management/generate-invoice",
        title: "Generate Invoice",
        moduleName: "generate-invoice",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Add Invoice"],
        submenu: [],
      },
      {
        path: "/admin/customer/invoices-management/pending-invoices",
        title: "Pending Invoices",
        moduleName: "pending-invoices",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Invoices"],
        submenu: [],
      },
      {
        path: "/admin/customer/invoices-management/approved-invoices",
        title: "Approved Invoices",
        moduleName: "approved-invoices",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Invoices"],
        submenu: [],
      },
      {
        path: "/admin/customer/invoices-management/rejected-invoices",
        title: "Rejected Invoices",
        moduleName: "rejected-invoices",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Invoices"],
        submenu: [],
      },
      {
        path: "/admin/customer/invoices-management/uploaded-invoices",
        title: "Uploaded Invoices",
        moduleName: "uploaded-invoices",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Invoices"],
        submenu: [],
      },
      {
        path: "/admin/customer/invoices-management/unsuccessful-ura-upload-invoices",
        title: "Unsuccessful Uploads",
        moduleName: "unsuccessful-invoices",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Invoices"],
        submenu: [],
      },
      // {
      //   path: "/user/customer/invoices-management/paid-invoices",
      //   title: "Paid Invoices",
      //   moduleName: "paid-invoices",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   submenu: [],
      // },
    ],
  },

  {
    path: "",
    title: "Credit Note Management",
    moduleName: "credit-management",
    iconType: "feather",
    icon: "file",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["View Credit Notes"],
    submenu: [
      {
        path: "/admin/customer/credit-notes-management/posted-invoices",
        title: "Uploaded Invoices",
        moduleName: "uploaded-invoices",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Credit Notes"],
        submenu: [],
      },
      {
        path: "/admin/customer/credit-notes-management/pending-credit-notes",
        title: "Pending Credit Notes",
        moduleName: "pending-credit-notes",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Credit Notes"],
        submenu: [],
      },
      {
        path: "/admin/customer/credit-notes-management/approved-credit-notes",
        title: "Approved Credit Notes",
        moduleName: "approved-credit-notes",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Credit Notes"],
        submenu: [],
      },
      {
        path: "/admin/customer/credit-notes-management/ura-uploaded-credit-notes",
        title: "Uploaded Credit Notes",
        moduleName: "ura-uploaded-credit-invoices",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Credit Notes"],
        submenu: [],
      },
      {
        path: "/admin/customer/credit-notes-management/failed-ura-credit-note-uploads",
        title: "Unsuccessful Uploads",
        moduleName: "unsuccessful-credit-note-uploads",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Credit Notes"],
        submenu: [],
      },
      {
        path: "/admin/customer/credit-notes-management/rejected-credit-notes",
        title: "Rejected Credit Notes",
        moduleName: "rejected-credit-notes",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Credit Notes"],
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "REPORTS",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["View Reports"],
    submenu: [],
  },
  {
    path: "/admin/reports/all",
    title: "Reports",
    moduleName: "reports",
    iconType: "feather",
    icon: "edit",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["View Reports"],
    submenu: [],
  },

  {
    path: "",
    title: "ACCOUNTS & ROLES MANAGEMENT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["View Roles", "View Users"],
    submenu: [],
  },
  {
    path: "",
    title: "Roles",
    moduleName: "RolesModule",
    iconType: "feather",
    icon: "book",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["View Roles"],
    submenu: [

      {
        path: "/admin/roles/add",
        title: "Add Role",
        moduleName: "RolesModule",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Add Roles"],
        submenu: [],
      },

      {
        path: "/admin/roles/view",
        title: "View Role",
        moduleName: "RolesModule",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Roles"],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "User Accounts",
    moduleName: "user-accounts",
    iconType: "feather",
    icon: "user",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["View Users"],
    submenu: [
      {
        path: "/admin/user-accounts/add-account",
        title: "Add Account",
        moduleName: "add-account",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Add User"],
        submenu: [],
      },

      // {
      //   path: "/admin/user-accounts/pending-accounts",
      //   title: "Pending Accounts",
      //   moduleName: "pending-accounts",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   privilege: ["View Users"],
      //   submenu: [],
      // },
      {
        path: "/admin/user-accounts/all",
        title: "Active Accounts",
        moduleName: "active-accounts",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Users"],
        submenu: [],
      },
      {
        path: "/admin/user-accounts/inactive-accounts",
        title: "Inactive Accounts",
        moduleName: "inactive-accounts",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Users"],
        submenu: [],
      },
      {
        path: "/admin/user-accounts/locked-accounts",
        title: "Locked Accounts",
        moduleName: "locked-accounts",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Users"],
        submenu: [],
      },
      {
        path: "/admin/user-accounts/deleted-accounts",
        title: "Deleted Accounts",
        moduleName: "deleted-accounts",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["View Users"],
        submenu: [],
      },
      // {
      //   path: "/admin/user-accounts/rejected-accounts",
      //   title: "Rejected Accounts",
      //   moduleName: "deleted-accounts",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   privilege: [""],
      //   submenu: [],
      // }
    ],
  },

  {
    path: "/account/update-profile",
    title: "Account Settings",
    moduleName: "admin",
    iconType: "feather",
    icon: "settings",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: [""],
    submenu: [],
  },



];
