//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.31 at 12:08:19 PM EAT 
//


package co.ke.emtechhouse.eims.Finacle.filookups.banks;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BodyBANKSHORTNAME_QNAME = new QName("", "BANK_SHORT_NAME");
    private final static QName _BodyBANKCODE_QNAME = new QName("", "BANK_CODE");
    private final static QName _BodyBANKNAME_QNAME = new QName("", "BANK_NAME");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BanksListBody }
     * 
     */
    public BanksListBody createBody() {
        return new BanksListBody();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BANK_SHORT_NAME", scope = BanksListBody.class)
    public JAXBElement<String> createBodyBANKSHORTNAME(String value) {
        return new JAXBElement<String>(_BodyBANKSHORTNAME_QNAME, String.class, BanksListBody.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BANK_CODE", scope = BanksListBody.class)
    public JAXBElement<String> createBodyBANKCODE(String value) {
        return new JAXBElement<String>(_BodyBANKCODE_QNAME, String.class, BanksListBody.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BANK_NAME", scope = BanksListBody.class)
    public JAXBElement<String> createBodyBANKNAME(String value) {
        return new JAXBElement<String>(_BodyBANKNAME_QNAME, String.class, BanksListBody.class, value);
    }

}
