//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.29 at 08:13:16 AM EAT 
//
package co.ke.emtechhouse.eims.TransactionComponent.FinacleService.FailureResponse;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ResponseHeader">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RequestMessageKey">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="GlobalUUID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ServiceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                       &lt;element name="ServiceVersion" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                       &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="OriginatorId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="OriginatorInstanceId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="OriginatorVersion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="LanguageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="ResponseMessageInfo">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                       &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="UBUSTransaction">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                                       &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="HostTransaction">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="HostParentTransaction">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="CustomInfo" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RateCodesBody">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Error">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="FIBusinessException">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ErrorDetail" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="ErrorDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="ErrorSource" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                                 &lt;element name="ErrorType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "body"
})
@XmlRootElement(name = "FIXML")
public class FIXML {

    @XmlElement(name = "Header", required = true)
    protected Header header;
    @XmlElement(name = "RateCodesBody", required = true)
    protected Body body;

    /**
     * Gets the value of the header property.
     *
     * @return
     *     possible object is
     *     {@link Header }
     *
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     *
     * @param value
     *     allowed object is
     *     {@link Header }
     *
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     *
     * @return
     *     possible object is
     *     {@link Body }
     *
     */
    public Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     *
     * @param value
     *     allowed object is
     *     {@link Body }
     *
     */
    public void setBody(Body value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Error">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="FIBusinessException">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ErrorDetail" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="ErrorDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="ErrorSource" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                                       &lt;element name="ErrorType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "error"
    })
    public static class Body {

        @XmlElement(name = "Error", required = true)
        protected Error error;

        /**
         * Gets the value of the error property.
         *
         * @return
         *     possible object is
         *     {@link Error }
         *
         */
        public Error getError() {
            return error;
        }

        /**
         * Sets the value of the error property.
         *
         * @param value
         *     allowed object is
         *     {@link Error }
         *
         */
        public void setError(Error value) {
            this.error = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="FIBusinessException">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ErrorDetail" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="ErrorDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="ErrorSource" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                             &lt;element name="ErrorType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fiBusinessException"
        })
        public static class Error {

            @XmlElement(name = "FIBusinessException", required = true)
            protected FIBusinessException fiBusinessException;

            /**
             * Gets the value of the fiBusinessException property.
             *
             * @return
             *     possible object is
             *     {@link FIBusinessException }
             *
             */
            public FIBusinessException getFIBusinessException() {
                return fiBusinessException;
            }

            /**
             * Sets the value of the fiBusinessException property.
             *
             * @param value
             *     allowed object is
             *     {@link FIBusinessException }
             *
             */
            public void setFIBusinessException(FIBusinessException value) {
                this.fiBusinessException = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ErrorDetail" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="ErrorDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="ErrorSource" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *                   &lt;element name="ErrorType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "errorDetail"
            })
            public static class FIBusinessException {

                @XmlElement(name = "ErrorDetail", required = true)
                protected List<ErrorDetail> errorDetail;

                /**
                 * Gets the value of the errorDetail property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the errorDetail property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getErrorDetail().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link ErrorDetail }
                 *
                 *
                 */
                public List<ErrorDetail> getErrorDetail() {
                    if (errorDetail == null) {
                        errorDetail = new ArrayList<ErrorDetail>();
                    }
                    return this.errorDetail;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="ErrorDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="ErrorSource" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                 *         &lt;element name="ErrorType" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "errorCode",
                    "errorDesc",
                    "errorSource",
                    "errorType"
                })
                public static class ErrorDetail {

                    @XmlElement(name = "ErrorCode", required = true)
                    protected String errorCode;
                    @XmlElement(name = "ErrorDesc", required = true)
                    protected String errorDesc;
                    @XmlElement(name = "ErrorSource", required = true)
                    protected Object errorSource;
                    @XmlElement(name = "ErrorType", required = true)
                    protected String errorType;

                    /**
                     * Gets the value of the errorCode property.
                     *
                     * @return
                     *     possible object is
                     *     {@link String }
                     *
                     */
                    public String getErrorCode() {
                        return errorCode;
                    }

                    /**
                     * Sets the value of the errorCode property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *
                     */
                    public void setErrorCode(String value) {
                        this.errorCode = value;
                    }

                    /**
                     * Gets the value of the errorDesc property.
                     *
                     * @return
                     *     possible object is
                     *     {@link String }
                     *
                     */
                    public String getErrorDesc() {
                        return errorDesc;
                    }

                    /**
                     * Sets the value of the errorDesc property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *
                     */
                    public void setErrorDesc(String value) {
                        this.errorDesc = value;
                    }

                    /**
                     * Gets the value of the errorSource property.
                     *
                     * @return
                     *     possible object is
                     *     {@link Object }
                     *
                     */
                    public Object getErrorSource() {
                        return errorSource;
                    }

                    /**
                     * Sets the value of the errorSource property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link Object }
                     *
                     */
                    public void setErrorSource(Object value) {
                        this.errorSource = value;
                    }

                    /**
                     * Gets the value of the errorType property.
                     *
                     * @return
                     *     possible object is
                     *     {@link String }
                     *
                     */
                    public String getErrorType() {
                        return errorType;
                    }

                    /**
                     * Sets the value of the errorType property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *
                     */
                    public void setErrorType(String value) {
                        this.errorType = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ResponseHeader">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RequestMessageKey">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="GlobalUUID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ServiceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                             &lt;element name="ServiceVersion" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                             &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="OriginatorId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="OriginatorInstanceId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="OriginatorVersion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="LanguageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="ResponseMessageInfo">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                             &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="UBUSTransaction">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *                             &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="HostTransaction">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="HostParentTransaction">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="CustomInfo" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "responseHeader"
    })
    public static class Header {

        @XmlElement(name = "ResponseHeader", required = true)
        protected ResponseHeader responseHeader;

        /**
         * Gets the value of the responseHeader property.
         *
         * @return
         *     possible object is
         *     {@link ResponseHeader }
         *
         */
        public ResponseHeader getResponseHeader() {
            return responseHeader;
        }

        /**
         * Sets the value of the responseHeader property.
         *
         * @param value
         *     allowed object is
         *     {@link ResponseHeader }
         *
         */
        public void setResponseHeader(ResponseHeader value) {
            this.responseHeader = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RequestMessageKey">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="GlobalUUID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ServiceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                   &lt;element name="ServiceVersion" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                   &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="OriginatorId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="OriginatorInstanceId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="OriginatorVersion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="LanguageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="ResponseMessageInfo">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                   &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="UBUSTransaction">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
         *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="HostTransaction">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="HostParentTransaction">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="CustomInfo" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "requestMessageKey",
            "responseMessageInfo",
            "ubusTransaction",
            "hostTransaction",
            "hostParentTransaction",
            "customInfo"
        })
        public static class ResponseHeader {

            @XmlElement(name = "RequestMessageKey", required = true)
            protected RequestMessageKey requestMessageKey;
            @XmlElement(name = "ResponseMessageInfo", required = true)
            protected ResponseMessageInfo responseMessageInfo;
            @XmlElement(name = "UBUSTransaction", required = true)
            protected UBUSTransaction ubusTransaction;
            @XmlElement(name = "HostTransaction", required = true)
            protected HostTransaction hostTransaction;
            @XmlElement(name = "HostParentTransaction", required = true)
            protected HostParentTransaction hostParentTransaction;
            @XmlElement(name = "CustomInfo", required = true)
            protected Object customInfo;

            /**
             * Gets the value of the requestMessageKey property.
             *
             * @return
             *     possible object is
             *     {@link RequestMessageKey }
             *
             */
            public RequestMessageKey getRequestMessageKey() {
                return requestMessageKey;
            }

            /**
             * Sets the value of the requestMessageKey property.
             *
             * @param value
             *     allowed object is
             *     {@link RequestMessageKey }
             *
             */
            public void setRequestMessageKey(RequestMessageKey value) {
                this.requestMessageKey = value;
            }

            /**
             * Gets the value of the responseMessageInfo property.
             *
             * @return
             *     possible object is
             *     {@link ResponseMessageInfo }
             *
             */
            public ResponseMessageInfo getResponseMessageInfo() {
                return responseMessageInfo;
            }

            /**
             * Sets the value of the responseMessageInfo property.
             *
             * @param value
             *     allowed object is
             *     {@link ResponseMessageInfo }
             *
             */
            public void setResponseMessageInfo(ResponseMessageInfo value) {
                this.responseMessageInfo = value;
            }

            /**
             * Gets the value of the ubusTransaction property.
             *
             * @return
             *     possible object is
             *     {@link UBUSTransaction }
             *
             */
            public UBUSTransaction getUBUSTransaction() {
                return ubusTransaction;
            }

            /**
             * Sets the value of the ubusTransaction property.
             *
             * @param value
             *     allowed object is
             *     {@link UBUSTransaction }
             *
             */
            public void setUBUSTransaction(UBUSTransaction value) {
                this.ubusTransaction = value;
            }

            /**
             * Gets the value of the hostTransaction property.
             *
             * @return
             *     possible object is
             *     {@link HostTransaction }
             *
             */
            public HostTransaction getHostTransaction() {
                return hostTransaction;
            }

            /**
             * Sets the value of the hostTransaction property.
             *
             * @param value
             *     allowed object is
             *     {@link HostTransaction }
             *
             */
            public void setHostTransaction(HostTransaction value) {
                this.hostTransaction = value;
            }

            /**
             * Gets the value of the hostParentTransaction property.
             *
             * @return
             *     possible object is
             *     {@link HostParentTransaction }
             *
             */
            public HostParentTransaction getHostParentTransaction() {
                return hostParentTransaction;
            }

            /**
             * Sets the value of the hostParentTransaction property.
             *
             * @param value
             *     allowed object is
             *     {@link HostParentTransaction }
             *
             */
            public void setHostParentTransaction(HostParentTransaction value) {
                this.hostParentTransaction = value;
            }

            /**
             * Gets the value of the customInfo property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getCustomInfo() {
                return customInfo;
            }

            /**
             * Sets the value of the customInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setCustomInfo(Object value) {
                this.customInfo = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "id",
                "status"
            })
            public static class HostParentTransaction {

                @XmlElement(name = "Id", required = true)
                protected String id;
                @XmlElement(name = "Status", required = true)
                protected String status;

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setId(String value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the status property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStatus() {
                    return status;
                }

                /**
                 * Sets the value of the status property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStatus(String value) {
                    this.status = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "id",
                "status"
            })
            public static class HostTransaction {

                @XmlElement(name = "Id", required = true)
                protected String id;
                @XmlElement(name = "Status", required = true)
                protected String status;

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setId(String value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the status property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStatus() {
                    return status;
                }

                /**
                 * Sets the value of the status property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStatus(String value) {
                    this.status = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="GlobalUUID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ServiceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *         &lt;element name="ServiceVersion" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *         &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="OriginatorId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="OriginatorInstanceId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="OriginatorVersion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="LanguageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "globalUUID",
                "requestUUID",
                "serviceRequestId",
                "serviceId",
                "serviceRequestVersion",
                "serviceVersion",
                "channelId",
                "originatorId",
                "originatorInstanceId",
                "originatorVersion",
                "languageId"
            })
            public static class RequestMessageKey {

                @XmlElement(name = "GlobalUUID", required = true)
                protected Object globalUUID;
                @XmlElement(name = "RequestUUID", required = true)
                protected String requestUUID;
                @XmlElement(name = "ServiceRequestId", required = true)
                protected String serviceRequestId;
                @XmlElement(name = "ServiceId", required = true)
                protected String serviceId;
                @XmlElement(name = "ServiceRequestVersion", required = true)
                protected BigDecimal serviceRequestVersion;
                @XmlElement(name = "ServiceVersion", required = true)
                protected BigDecimal serviceVersion;
                @XmlElement(name = "ChannelId", required = true)
                protected String channelId;
                @XmlElement(name = "OriginatorId", required = true)
                protected String originatorId;
                @XmlElement(name = "OriginatorInstanceId", required = true)
                protected Object originatorInstanceId;
                @XmlElement(name = "OriginatorVersion", required = true)
                protected Object originatorVersion;
                @XmlElement(name = "LanguageId", required = true)
                protected String languageId;

                /**
                 * Gets the value of the globalUUID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getGlobalUUID() {
                    return globalUUID;
                }

                /**
                 * Sets the value of the globalUUID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setGlobalUUID(Object value) {
                    this.globalUUID = value;
                }

                /**
                 * Gets the value of the requestUUID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRequestUUID() {
                    return requestUUID;
                }

                /**
                 * Sets the value of the requestUUID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRequestUUID(String value) {
                    this.requestUUID = value;
                }

                /**
                 * Gets the value of the serviceRequestId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getServiceRequestId() {
                    return serviceRequestId;
                }

                /**
                 * Sets the value of the serviceRequestId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setServiceRequestId(String value) {
                    this.serviceRequestId = value;
                }

                /**
                 * Gets the value of the serviceId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getServiceId() {
                    return serviceId;
                }

                /**
                 * Sets the value of the serviceId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setServiceId(String value) {
                    this.serviceId = value;
                }

                /**
                 * Gets the value of the serviceRequestVersion property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getServiceRequestVersion() {
                    return serviceRequestVersion;
                }

                /**
                 * Sets the value of the serviceRequestVersion property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setServiceRequestVersion(BigDecimal value) {
                    this.serviceRequestVersion = value;
                }

                /**
                 * Gets the value of the serviceVersion property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getServiceVersion() {
                    return serviceVersion;
                }

                /**
                 * Sets the value of the serviceVersion property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setServiceVersion(BigDecimal value) {
                    this.serviceVersion = value;
                }

                /**
                 * Gets the value of the channelId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getChannelId() {
                    return channelId;
                }

                /**
                 * Sets the value of the channelId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setChannelId(String value) {
                    this.channelId = value;
                }

                /**
                 * Gets the value of the originatorId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOriginatorId() {
                    return originatorId;
                }

                /**
                 * Sets the value of the originatorId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOriginatorId(String value) {
                    this.originatorId = value;
                }

                /**
                 * Gets the value of the originatorInstanceId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getOriginatorInstanceId() {
                    return originatorInstanceId;
                }

                /**
                 * Sets the value of the originatorInstanceId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setOriginatorInstanceId(Object value) {
                    this.originatorInstanceId = value;
                }

                /**
                 * Gets the value of the originatorVersion property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getOriginatorVersion() {
                    return originatorVersion;
                }

                /**
                 * Sets the value of the originatorVersion property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setOriginatorVersion(Object value) {
                    this.originatorVersion = value;
                }

                /**
                 * Gets the value of the languageId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLanguageId() {
                    return languageId;
                }

                /**
                 * Sets the value of the languageId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLanguageId(String value) {
                    this.languageId = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *         &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "bankId",
                "timeZone",
                "messageDateTime"
            })
            public static class ResponseMessageInfo {

                @XmlElement(name = "BankId")
                @XmlSchemaType(name = "unsignedByte")
                protected short bankId;
                @XmlElement(name = "TimeZone", required = true)
                protected String timeZone;
                @XmlElement(name = "MessageDateTime", required = true)
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar messageDateTime;

                /**
                 * Gets the value of the bankId property.
                 * 
                 */
                public short getBankId() {
                    return bankId;
                }

                /**
                 * Sets the value of the bankId property.
                 * 
                 */
                public void setBankId(short value) {
                    this.bankId = value;
                }

                /**
                 * Gets the value of the timeZone property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTimeZone() {
                    return timeZone;
                }

                /**
                 * Sets the value of the timeZone property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTimeZone(String value) {
                    this.timeZone = value;
                }

                /**
                 * Gets the value of the messageDateTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getMessageDateTime() {
                    return messageDateTime;
                }

                /**
                 * Sets the value of the messageDateTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setMessageDateTime(XMLGregorianCalendar value) {
                    this.messageDateTime = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
             *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "id",
                "status"
            })
            public static class UBUSTransaction {

                @XmlElement(name = "Id")
                @XmlSchemaType(name = "unsignedShort")
                protected int id;
                @XmlElement(name = "Status", required = true)
                protected String status;

                /**
                 * Gets the value of the id property.
                 * 
                 */
                public int getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 */
                public void setId(int value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the status property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStatus() {
                    return status;
                }

                /**
                 * Sets the value of the status property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStatus(String value) {
                    this.status = value;
                }

            }

        }

    }

}
