//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.08 at 05:55:16 PM EAT 
//


package co.ke.emtechhouse.eims.TransactionComponent.FinacleService.FIXMLS;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ResponseHeader">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RequestMessageKey">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                       &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="ResponseMessageInfo">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                       &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="UBUSTransaction">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="HostTransaction">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="HostParentTransaction">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="CustomInfo" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RateCodesBody">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="XferTrnAddResponse">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="XferTrnAddRs">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="TrnIdentifier">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="TrnDt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                                 &lt;element name="TrnId" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="XferTrnAdd_CustomData" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "header",
        "body"
})
@XmlRootElement(name = "FIXML")
public class FIXML {

    @XmlElement(name = "Header", required = true)
    protected Header header;
    @XmlElement(name = "RateCodesBody", required = true)
    protected Body body;

    /**
     * Gets the value of the header property.
     *
     * @return
     *     possible object is
     *     {@link Header }
     *
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     *
     * @param value
     *     allowed object is
     *     {@link Header }
     *
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     *
     * @return
     *     possible object is
     *     {@link Body }
     *
     */
    public Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     *
     * @param value
     *     allowed object is
     *     {@link Body }
     *
     */
    public void setBody(Body value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="XferTrnAddResponse">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="XferTrnAddRs">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="TrnIdentifier">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="TrnDt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                                       &lt;element name="TrnId" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="XferTrnAdd_CustomData" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "xferTrnAddResponse"
    })
    public static class Body {

        @XmlElement(name = "XferTrnAddResponse", required = true)
        protected XferTrnAddResponse xferTrnAddResponse;

        /**
         * Gets the value of the xferTrnAddResponse property.
         *
         * @return
         *     possible object is
         *     {@link XferTrnAddResponse }
         *
         */
        public XferTrnAddResponse getXferTrnAddResponse() {
            return xferTrnAddResponse;
        }

        /**
         * Sets the value of the xferTrnAddResponse property.
         *
         * @param value
         *     allowed object is
         *     {@link XferTrnAddResponse }
         *
         */
        public void setXferTrnAddResponse(XferTrnAddResponse value) {
            this.xferTrnAddResponse = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="XferTrnAddRs">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="TrnIdentifier">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="TrnDt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *                             &lt;element name="TrnId" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="XferTrnAdd_CustomData" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "xferTrnAddRs",
                "xferTrnAddCustomData"
        })
        public static class XferTrnAddResponse {

            @XmlElement(name = "XferTrnAddRs", required = true)
            protected XferTrnAddRs xferTrnAddRs;
            @XmlElement(name = "XferTrnAdd_CustomData", required = true)
            protected Object xferTrnAddCustomData;

            /**
             * Gets the value of the xferTrnAddRs property.
             *
             * @return
             *     possible object is
             *     {@link XferTrnAddRs }
             *
             */
            public XferTrnAddRs getXferTrnAddRs() {
                return xferTrnAddRs;
            }

            /**
             * Sets the value of the xferTrnAddRs property.
             *
             * @param value
             *     allowed object is
             *     {@link XferTrnAddRs }
             *
             */
            public void setXferTrnAddRs(XferTrnAddRs value) {
                this.xferTrnAddRs = value;
            }

            /**
             * Gets the value of the xferTrnAddCustomData property.
             *
             * @return
             *     possible object is
             *     {@link Object }
             *
             */
            public Object getXferTrnAddCustomData() {
                return xferTrnAddCustomData;
            }

            /**
             * Sets the value of the xferTrnAddCustomData property.
             *
             * @param value
             *     allowed object is
             *     {@link Object }
             *
             */
            public void setXferTrnAddCustomData(Object value) {
                this.xferTrnAddCustomData = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="TrnIdentifier">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="TrnDt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
             *                   &lt;element name="TrnId" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "trnIdentifier"
            })
            public static class XferTrnAddRs {

                @XmlElement(name = "TrnIdentifier", required = true)
                protected TrnIdentifier trnIdentifier;

                /**
                 * Gets the value of the trnIdentifier property.
                 *
                 * @return
                 *     possible object is
                 *     {@link TrnIdentifier }
                 *
                 */
                public TrnIdentifier getTrnIdentifier() {
                    return trnIdentifier;
                }

                /**
                 * Sets the value of the trnIdentifier property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link TrnIdentifier }
                 *
                 */
                public void setTrnIdentifier(TrnIdentifier value) {
                    this.trnIdentifier = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="TrnDt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
                 *         &lt;element name="TrnId" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                        "trnDt",
                        "trnId"
                })
                public static class TrnIdentifier {

                    @XmlElement(name = "TrnDt", required = true)
                    @XmlSchemaType(name = "dateTime")
                    protected XMLGregorianCalendar trnDt;
                    @XmlElement(name = "TrnId")
                    @XmlSchemaType(name = "unsignedShort")
                    protected String trnId;

                    /**
                     * Gets the value of the trnDt property.
                     *
                     * @return
                     *     possible object is
                     *     {@link XMLGregorianCalendar }
                     *
                     */
                    public XMLGregorianCalendar getTrnDt() {
                        return trnDt;
                    }

                    /**
                     * Sets the value of the trnDt property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link XMLGregorianCalendar }
                     *
                     */
                    public void setTrnDt(XMLGregorianCalendar value) {
                        this.trnDt = value;
                    }

                    /**
                     * Gets the value of the trnId property.
                     *
                     */
                    public String getTrnId() {
                        return trnId;
                    }

                    /**
                     * Sets the value of the trnId property.
                     *
                     */
                    public void setTrnId(String value) {
                        this.trnId = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ResponseHeader">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RequestMessageKey">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                             &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="ResponseMessageInfo">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                             &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="UBUSTransaction">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="HostTransaction">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="HostParentTransaction">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="CustomInfo" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "responseHeader"
    })
    public static class Header {

        @XmlElement(name = "ResponseHeader", required = true)
        protected ResponseHeader responseHeader;

        /**
         * Gets the value of the responseHeader property.
         *
         * @return
         *     possible object is
         *     {@link ResponseHeader }
         *
         */
        public ResponseHeader getResponseHeader() {
            return responseHeader;
        }

        /**
         * Sets the value of the responseHeader property.
         *
         * @param value
         *     allowed object is
         *     {@link ResponseHeader }
         *
         */
        public void setResponseHeader(ResponseHeader value) {
            this.responseHeader = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RequestMessageKey">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                   &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="ResponseMessageInfo">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                   &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="UBUSTransaction">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="HostTransaction">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="HostParentTransaction">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="CustomInfo" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "requestMessageKey",
                "responseMessageInfo",
                "ubusTransaction",
                "hostTransaction",
                "hostParentTransaction",
                "customInfo"
        })
        public static class ResponseHeader {

            @XmlElement(name = "RequestMessageKey", required = true)
            protected RequestMessageKey requestMessageKey;
            @XmlElement(name = "ResponseMessageInfo", required = true)
            protected ResponseMessageInfo responseMessageInfo;
            @XmlElement(name = "UBUSTransaction", required = true)
            protected UBUSTransaction ubusTransaction;
            @XmlElement(name = "HostTransaction", required = true)
            protected HostTransaction hostTransaction;
            @XmlElement(name = "HostParentTransaction", required = true)
            protected HostParentTransaction hostParentTransaction;
            @XmlElement(name = "CustomInfo", required = true)
            protected Object customInfo;

            /**
             * Gets the value of the requestMessageKey property.
             *
             * @return
             *     possible object is
             *     {@link RequestMessageKey }
             *
             */
            public RequestMessageKey getRequestMessageKey() {
                return requestMessageKey;
            }

            /**
             * Sets the value of the requestMessageKey property.
             *
             * @param value
             *     allowed object is
             *     {@link RequestMessageKey }
             *
             */
            public void setRequestMessageKey(RequestMessageKey value) {
                this.requestMessageKey = value;
            }

            /**
             * Gets the value of the responseMessageInfo property.
             *
             * @return
             *     possible object is
             *     {@link ResponseMessageInfo }
             *
             */
            public ResponseMessageInfo getResponseMessageInfo() {
                return responseMessageInfo;
            }

            /**
             * Sets the value of the responseMessageInfo property.
             *
             * @param value
             *     allowed object is
             *     {@link ResponseMessageInfo }
             *
             */
            public void setResponseMessageInfo(ResponseMessageInfo value) {
                this.responseMessageInfo = value;
            }

            /**
             * Gets the value of the ubusTransaction property.
             *
             * @return
             *     possible object is
             *     {@link UBUSTransaction }
             *
             */
            public UBUSTransaction getUBUSTransaction() {
                return ubusTransaction;
            }

            /**
             * Sets the value of the ubusTransaction property.
             *
             * @param value
             *     allowed object is
             *     {@link UBUSTransaction }
             *
             */
            public void setUBUSTransaction(UBUSTransaction value) {
                this.ubusTransaction = value;
            }

            /**
             * Gets the value of the hostTransaction property.
             *
             * @return
             *     possible object is
             *     {@link HostTransaction }
             *
             */
            public HostTransaction getHostTransaction() {
                return hostTransaction;
            }

            /**
             * Sets the value of the hostTransaction property.
             *
             * @param value
             *     allowed object is
             *     {@link HostTransaction }
             *
             */
            public void setHostTransaction(HostTransaction value) {
                this.hostTransaction = value;
            }

            /**
             * Gets the value of the hostParentTransaction property.
             *
             * @return
             *     possible object is
             *     {@link HostParentTransaction }
             *
             */
            public HostParentTransaction getHostParentTransaction() {
                return hostParentTransaction;
            }

            /**
             * Sets the value of the hostParentTransaction property.
             *
             * @param value
             *     allowed object is
             *     {@link HostParentTransaction }
             *
             */
            public void setHostParentTransaction(HostParentTransaction value) {
                this.hostParentTransaction = value;
            }

            /**
             * Gets the value of the customInfo property.
             *
             * @return
             *     possible object is
             *     {@link Object }
             *
             */
            public Object getCustomInfo() {
                return customInfo;
            }

            /**
             * Sets the value of the customInfo property.
             *
             * @param value
             *     allowed object is
             *     {@link Object }
             *
             */
            public void setCustomInfo(Object value) {
                this.customInfo = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "id",
                    "status"
            })
            public static class HostParentTransaction {

                @XmlElement(name = "Id", required = true)
                protected Object id;
                @XmlElement(name = "Status", required = true)
                protected Object status;

                /**
                 * Gets the value of the id property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *
                 */
                public Object getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *
                 */
                public void setId(Object value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the status property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *
                 */
                public Object getStatus() {
                    return status;
                }

                /**
                 * Sets the value of the status property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *
                 */
                public void setStatus(Object value) {
                    this.status = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "id",
                    "status"
            })
            public static class HostTransaction {

                @XmlElement(name = "Id", required = true)
                protected Object id;
                @XmlElement(name = "Status", required = true)
                protected String status;

                /**
                 * Gets the value of the id property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *
                 */
                public Object getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *
                 */
                public void setId(Object value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the status property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getStatus() {
                    return status;
                }

                /**
                 * Sets the value of the status property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setStatus(String value) {
                    this.status = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *         &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "requestUUID",
                    "serviceRequestId",
                    "serviceRequestVersion",
                    "channelId"
            })
            public static class RequestMessageKey {

                @XmlElement(name = "RequestUUID", required = true)
                protected String requestUUID;
                @XmlElement(name = "ServiceRequestId", required = true)
                protected String serviceRequestId;
                @XmlElement(name = "ServiceRequestVersion", required = true)
                protected BigDecimal serviceRequestVersion;
                @XmlElement(name = "ChannelId", required = true)
                protected String channelId;

                /**
                 * Gets the value of the requestUUID property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getRequestUUID() {
                    return requestUUID;
                }

                /**
                 * Sets the value of the requestUUID property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setRequestUUID(String value) {
                    this.requestUUID = value;
                }

                /**
                 * Gets the value of the serviceRequestId property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getServiceRequestId() {
                    return serviceRequestId;
                }

                /**
                 * Sets the value of the serviceRequestId property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setServiceRequestId(String value) {
                    this.serviceRequestId = value;
                }

                /**
                 * Gets the value of the serviceRequestVersion property.
                 *
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *
                 */
                public BigDecimal getServiceRequestVersion() {
                    return serviceRequestVersion;
                }

                /**
                 * Sets the value of the serviceRequestVersion property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *
                 */
                public void setServiceRequestVersion(BigDecimal value) {
                    this.serviceRequestVersion = value;
                }

                /**
                 * Gets the value of the channelId property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getChannelId() {
                    return channelId;
                }

                /**
                 * Sets the value of the channelId property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setChannelId(String value) {
                    this.channelId = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *         &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "bankId",
                    "timeZone",
                    "messageDateTime"
            })
            public static class ResponseMessageInfo {

                @XmlElement(name = "BankId")
                @XmlSchemaType(name = "unsignedByte")
                protected short bankId;
                @XmlElement(name = "TimeZone", required = true)
                protected String timeZone;
                @XmlElement(name = "MessageDateTime", required = true)
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar messageDateTime;

                /**
                 * Gets the value of the bankId property.
                 *
                 */
                public short getBankId() {
                    return bankId;
                }

                /**
                 * Sets the value of the bankId property.
                 *
                 */
                public void setBankId(short value) {
                    this.bankId = value;
                }

                /**
                 * Gets the value of the timeZone property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getTimeZone() {
                    return timeZone;
                }

                /**
                 * Sets the value of the timeZone property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setTimeZone(String value) {
                    this.timeZone = value;
                }

                /**
                 * Gets the value of the messageDateTime property.
                 *
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *
                 */
                public XMLGregorianCalendar getMessageDateTime() {
                    return messageDateTime;
                }

                /**
                 * Sets the value of the messageDateTime property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *
                 */
                public void setMessageDateTime(XMLGregorianCalendar value) {
                    this.messageDateTime = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "id",
                    "status"
            })
            public static class UBUSTransaction {

                @XmlElement(name = "Id", required = true)
                protected Object id;
                @XmlElement(name = "Status", required = true)
                protected Object status;

                /**
                 * Gets the value of the id property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *
                 */
                public Object getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *
                 */
                public void setId(Object value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the status property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *
                 */
                public Object getStatus() {
                    return status;
                }

                /**
                 * Sets the value of the status property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *
                 */
                public void setStatus(Object value) {
                    this.status = value;
                }

            }

        }

    }

}
