//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.08 at 05:55:16 PM EAT 
//


package co.ke.emtechhouse.eims.TransactionComponent.FinacleService.FIXMLS;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.finacle.fixml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.finacle.fixml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FIXML }
     * 
     */
    public FIXML createFIXML() {
        return new FIXML();
    }

    /**
     * Create an instance of {@link FIXML.Body }
     * 
     */
    public FIXML.Body createFIXMLBody() {
        return new FIXML.Body();
    }

    /**
     * Create an instance of {@link FIXML.Body.XferTrnAddResponse }
     * 
     */
    public FIXML.Body.XferTrnAddResponse createFIXMLBodyXferTrnAddResponse() {
        return new FIXML.Body.XferTrnAddResponse();
    }

    /**
     * Create an instance of {@link FIXML.Body.XferTrnAddResponse.XferTrnAddRs }
     * 
     */
    public FIXML.Body.XferTrnAddResponse.XferTrnAddRs createFIXMLBodyXferTrnAddResponseXferTrnAddRs() {
        return new FIXML.Body.XferTrnAddResponse.XferTrnAddRs();
    }

    /**
     * Create an instance of {@link FIXML.Header }
     * 
     */
    public FIXML.Header createFIXMLHeader() {
        return new FIXML.Header();
    }

    /**
     * Create an instance of {@link FIXML.Header.ResponseHeader }
     * 
     */
    public FIXML.Header.ResponseHeader createFIXMLHeaderResponseHeader() {
        return new FIXML.Header.ResponseHeader();
    }

    /**
     * Create an instance of {@link FIXML.Body.XferTrnAddResponse.XferTrnAddRs.TrnIdentifier }
     * 
     */
    public FIXML.Body.XferTrnAddResponse.XferTrnAddRs.TrnIdentifier createFIXMLBodyXferTrnAddResponseXferTrnAddRsTrnIdentifier() {
        return new FIXML.Body.XferTrnAddResponse.XferTrnAddRs.TrnIdentifier();
    }

    /**
     * Create an instance of {@link FIXML.Header.ResponseHeader.RequestMessageKey }
     * 
     */
    public FIXML.Header.ResponseHeader.RequestMessageKey createFIXMLHeaderResponseHeaderRequestMessageKey() {
        return new FIXML.Header.ResponseHeader.RequestMessageKey();
    }

    /**
     * Create an instance of {@link FIXML.Header.ResponseHeader.ResponseMessageInfo }
     * 
     */
    public FIXML.Header.ResponseHeader.ResponseMessageInfo createFIXMLHeaderResponseHeaderResponseMessageInfo() {
        return new FIXML.Header.ResponseHeader.ResponseMessageInfo();
    }

    /**
     * Create an instance of {@link FIXML.Header.ResponseHeader.UBUSTransaction }
     * 
     */
    public FIXML.Header.ResponseHeader.UBUSTransaction createFIXMLHeaderResponseHeaderUBUSTransaction() {
        return new FIXML.Header.ResponseHeader.UBUSTransaction();
    }

    /**
     * Create an instance of {@link FIXML.Header.ResponseHeader.HostTransaction }
     * 
     */
    public FIXML.Header.ResponseHeader.HostTransaction createFIXMLHeaderResponseHeaderHostTransaction() {
        return new FIXML.Header.ResponseHeader.HostTransaction();
    }

    /**
     * Create an instance of {@link FIXML.Header.ResponseHeader.HostParentTransaction }
     * 
     */
    public FIXML.Header.ResponseHeader.HostParentTransaction createFIXMLHeaderResponseHeaderHostParentTransaction() {
        return new FIXML.Header.ResponseHeader.HostParentTransaction();
    }

}
