//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.08 at 05:55:16 PM EAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.finacle.com/fixml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package co.ke.emtechhouse.eims.TransactionComponent.FinacleService.FIXMLS;
